from datetime import date


class MockPerf:
    header = ['weighted_avg_maturity',
              'weighted_avg_life',
              'daily_maturing_asset_pct',
              'weekly_maturing_asset_pct',
              'ls1d_liquid',
              'd2t7_liquid',
              'd829_liquid',
              'a30d_liquid',
              'base_ccy_nav',
              'report_ccy_nav',
              'lt3m_perf',
              'lt1m_perf',
              'lt1y_perf',
              'lt3y_perf',
              'lt5y_perf',
              'cytd_perf',
              'lt1y_vol',
              'lt2y_vol',
              'lt3y_vol',
              'lt1y_shadow_vol',
              'lt2y_shadow_vol',
              'lt3y_shadow_vol',
              'yms2_perf',
              'ymn3_perf',
              'yms1_perf'
              ]
    data = [0.9,
            0.9,
            0.2,
            0.3,
            0.2,
            0.21,
            0.22,
            0.22,
            100.01,
            100.02,
            0.11,
            0.12,
            0.13,
            0.14,
            0.15,
            0.16,
            0.05,
            0.06,
            0.07,
            0.051,
            0.052,
            0.053,
            0.111,
            0.122,
            0.133
            ]


class MockLiability:
    header = [
        "highest_beneficial_owner_pct",
        "prof_estimated_rate",
        "prof_precise_rate",
        "retail_estimated_rate",
        "retail_precise_rate",
        "investor_bank_pct",
        "investor_general_govt_pct",
        "investor_household_pct",
        "investor_insurance_pct",
        "investor_non_fin_pct",
        "investor_mmf_pct",
        "investor_other_fin_pct",
        "investor_pension_fund_pct",
        "investor_unknown_pct",
        "country_breakdown_pct",
        "redemption_frequency",
        "notice_period",
        "arrangement_breakdown_pct",
        "other_arrangement",
        "monthly_nav",
        "monthly_subs",
        "monthly_redemption",
        "monthly_payment",
        "monthly_xrate"

    ]
    data = [0.2,
            0.9,
            0.91,
            0.1,
            0.09,
            0.1,
            0.1,
            0.1,
            0.1,
            0.1,
            0.1,
            0.1,
            0.1,
            0.2,
            [{'FR': 0.5}, {'GB': 0.2}, {'US': 0.3}],
            'daily',
            3,
            [{'SPRN': 0.2}, {'GATE': 0.1}, {'RDLF': 0.1}, {'OTHR': 0.5}],
            'None',
            [100 + m + 1 for m in range(12)],
            [(m + 1) / 100 for m in range(12)],
            [(m + 1) / 200 for m in range(12)],
            [0.05 for _ in range(12)],
            [{'ccy': 'USD', 'xrate': 0.9} for _ in range(12)]
            ]


class MockStressTest:
    header = [
        "test_date",
        "net_asset_value_basis",
        "code",
        "impact",
        "input_factor",
        "comment",
        "action_plan",
        "fund_code"
    ]
    data = [[date.today(),
             'cnav',
             'code 1',
             '0.74',
             None,
             None,
             'A plan',
             'FCD1'
             ]]
